#!/usr/bin/env python3
import os
import argparse
from astropy.table import Table, setdiff

from table_tools import load_table


if __name__ == "__main__":

    parser = argparse.ArgumentParser(
        description='Create a new table from objects with an unique object '
                    'identifier which exist in table 1 but not in table 2.')
    parser.add_argument(
        '-i', '--input', required=True,
        help='file path of input data table 1')
    parser.add_argument(
        '--i-format', default='fits',
        help='astropy.table format specifier of table 2')
    parser.add_argument(
        '-d', '--diff', required=True,
        help='file path of input data table 2 which will be subtracted from '
             'table 1')
    parser.add_argument(
        "--d-format", default='fits',
        help='astropy.table format specifier of table 2')
    parser.add_argument(
        '--keys', required=True, help='object indetifier column name')
    parser.add_argument(
        '-o', '--output', required=True, help='file path of output table')
    parser.add_argument(
        '--o-format', default='fits',
        help='astropy.table format specifier of the output table '
             '(default: %(default)s)')
    args = parser.parse_args()

    # load data
    table1 = load_table(args.input, args.i_format, [args.keys], tabinfo=" (1)")
    table2 = load_table(args.diff, args.d_format, [args.keys], tabinfo=" (2)")

    print(
        "only keep entries from column '%s' in (1) which do not exist in (2)" %
        args.keys)
    table = setdiff(table1, table2, keys=[args.keys])

    # write to specified output path
    print("write table to: %s" % args.output)
    table.write(args.output, format=args.o_format, overwrite=True)
